### PR TITLE
Update version to 3.9.2

### PR DESCRIPTION
**Pull request by dalcinl**

### CODE REVIEW

**Comment by dalcinl** [comment]
@minrk Please do not merge, there is a new PETSc release out, I would like to get that one in first.

**Comment by minrk** [comment]
petsc 3.9.3 has landed. Feel free to merge or trigger new builds as you see fit.

**Comment by dalcinl** [comment]
I prefer to trigger a new build, just in case something went wrong in the petsc build.

**Comment by dalcinl** [comment]
Closed in favor of #17.

**Pull request closed without merging**
