### PR TITLE
update openblas pin

### PR DESCRIPTION
**Pull request by minrk**
and update format so pinning bot will find it in the future

### CODE REVIEW

**Comment by minrk** [comment]
@dalcinl looks like the updated petsc 3.8.3 has something wrong in its build config.

**Comment by dalcinl** [comment]
@minrk Yes, now that PETSc is built with Fortran support, we need to update the SLEPc recipe. I would decline this PR, I'm about to make a new one with this [branch](https://github.com/dalcinl/slepc-feedstock/tree/update-3.8.2), it already contains your openblas version update, plus the required changes to buils the Fortran wrappers. Please confirm you are OK with this.

**Comment by dalcinl** [comment]
Oh, I see. I should really implement your format change for the pinning bot to work in the future, right? I'll do it right now, and submit a new PR.

**Comment by minrk** [comment]
Thanks! I think there's still something wrong in petsc's build files, but they are not super important. PETSC_*LIB makefile variables include a bunch of libraries that aren't needed. They use PETSC_WITH_EXTERNAL_LIB where they should be using PETSC_LIB (`-lpetsc`) alone instead.

**Comment by dalcinl** [comment]
Well, remember that PETSc makefiles are supposed to work with shared as well as static library builds, and they are not yet prepared to make a distinction, so they use `PETSC_WITH_EXTERNAL_LIB`.

**Pull request closed without merging**
