### PR TITLE
Build long prefix package using conda-build 2.x

### PR DESCRIPTION
**Pull request by jjhelmus**

### CODE REVIEW

**Comment by jjhelmus** [comment]
I think this will fail... but want to see for sure.

**Comment by minrk** [comment]
I fixed the petsc pacakge, so this one should pass on circle now if you can restart it.

**Comment by jakirkham** [comment]
Toggling for CIs. Note we have enabled CircleCI builds for PRs from forks for all current feedstocks.

**Comment by jakirkham** [comment]
Guess that is not going to work. Take this as a reminder that we will need to disable CircleCI on all forks to get CircleCI to build under the conda-forge org account again.

**Comment by jakirkham** [comment]
Pushed an empty commit to your branch, @jjhelmus, to get CircleCI running. Hope that is ok. 😁

**Comment by minrk** [comment]
Circle passes! And [Travis passed](https://travis-ci.org/conda-forge/slepc-feedstock/builds/185892238) [before the empty commits](https://github.com/conda-forge/slepc-feedstock/compare/a74fdcf...436642a), so merging now.

**Comment by jakirkham** [comment]
:tada: Awesome!

Were there other things that we needed to rebuild in this part of the stack or was that it?

**Pull request merged**
